-- MySQL Script generated by MySQL Workbench
-- Wed May 22 10:39:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema umd-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema umd-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `umd-db` DEFAULT CHARACTER SET utf8 ;
USE `umd-db` ;

-- -----------------------------------------------------
-- Table `umd-db`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umd-db`.`customer` ;

CREATE TABLE IF NOT EXISTS `umd-db`.`customer` (
  `cust_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NULL DEFAULT NULL,
  `last_name` VARCHAR(30) NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `phone_no` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `account_no` INT(9) NULL DEFAULT NULL,
  `uname` VARCHAR(30) NULL DEFAULT NULL,
  `pwd` VARCHAR(30) NULL DEFAULT NULL,
  `pin` INT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`cust_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_no_UNIQUE` (`phone_no` ASC),
  UNIQUE INDEX `account_no_UNIQUE` (`account_no` ASC),
  UNIQUE INDEX `uname_UNIQUE` (`uname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umd-db`.`passbook1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umd-db`.`passbook1` ;

CREATE TABLE IF NOT EXISTS `umd-db`.`passbook1` (
  `trans_id` INT(11) NOT NULL,
  `trans_date` DATETIME NULL DEFAULT NULL,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  `debit` INT(11) NULL DEFAULT NULL,
  `credit` INT(11) NULL DEFAULT NULL,
  `balance` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`trans_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umd-db`.`passbook2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umd-db`.`passbook2` ;

CREATE TABLE IF NOT EXISTS `umd-db`.`passbook2` (
  `trans_id` INT(11) NOT NULL,
  `trans_date` DATETIME NULL DEFAULT NULL,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  `debit` INT(11) NULL DEFAULT NULL,
  `credit` INT(11) NULL DEFAULT NULL,
  `balance` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`trans_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umd-db`.`passbook3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umd-db`.`passbook3` ;

CREATE TABLE IF NOT EXISTS `umd-db`.`passbook3` (
  `trans_id` INT(11) NOT NULL,
  `trans_date` DATETIME NULL DEFAULT NULL,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  `debit` INT(11) NULL DEFAULT NULL,
  `credit` INT(11) NULL DEFAULT NULL,
  `balance` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`trans_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umd-db`.`passbook4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umd-db`.`passbook4` ;

CREATE TABLE IF NOT EXISTS `umd-db`.`passbook4` (
  `trans_id` INT(11) NOT NULL,
  `trans_date` DATETIME NULL DEFAULT NULL,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  `debit` INT(11) NULL DEFAULT NULL,
  `credit` INT(11) NULL DEFAULT NULL,
  `balance` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`trans_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `umd-db`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `umd-db`;
INSERT INTO `umd-db`.`customer` (`cust_id`, `first_name`, `last_name`, `gender`, `dob`, `email`, `phone_no`, `address`, `account_no`, `uname`, `pwd`, `pin`) VALUES (1, 'Paul', 'Shiller', 'male', '1996-04-06', 'pshiller@umd.edu', '+1 2678081972', '123 lane road, city, state 20740', 113547300, 'pshiller', 'password', 1996);
INSERT INTO `umd-db`.`customer` (`cust_id`, `first_name`, `last_name`, `gender`, `dob`, `email`, `phone_no`, `address`, `account_no`, `uname`, `pwd`, `pin`) VALUES (2, 'Bilbo', 'Baggins', 'male', '1997-03-11', 'bbaggins@umd.edu', '+1 2345678901', 'bags end, shire', 123456789, 'bbaggins', 'ring', 1997);
INSERT INTO `umd-db`.`customer` (`cust_id`, `first_name`, `last_name`, `gender`, `dob`, `email`, `phone_no`, `address`, `account_no`, `uname`, `pwd`, `pin`) VALUES (3, 'Mia', 'Khalifa', 'female', '1999-12-08', 'mkhalifa@umd.edu', '+1 2347898989', 'Cali', 987654321, 'mkhalifa', 'instagram', 1999);
INSERT INTO `umd-db`.`customer` (`cust_id`, `first_name`, `last_name`, `gender`, `dob`, `email`, `phone_no`, `address`, `account_no`, `uname`, `pwd`, `pin`) VALUES (4, 'Jon', 'Snow', 'male', '1998-09-09', 'jsnow@umd.edu', '+1 2345668901', 'The Night Watch,\r King in the North,\r The North Remembers,\r Westeros.', 796854321, 'jsnow', 'nightwatch', 1998);

COMMIT;


-- -----------------------------------------------------
-- Data for table `umd-db`.`passbook1`
-- -----------------------------------------------------
START TRANSACTION;
USE `umd-db`;
INSERT INTO `umd-db`.`passbook1` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (1, '2018-09-06 22:18:36', 'PRIOR BALANCE', 4164.27, 0, -4164.27);
INSERT INTO `umd-db`.`passbook1` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (2, '2018-10-02 18:49:26', 'UNSUB DIRECT LOAN', 0, 1412, -2757.27);
INSERT INTO `umd-db`.`passbook1` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (3, '2018-10-02 21:02:32', 'SUB DIRECT LOAN', 0, 1557, -1195.27);
INSERT INTO `umd-db`.`passbook1` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (4, '2018-10-05 20:11:33', 'TUITION', 2571, 0, -3766);
INSERT INTO `umd-db`.`passbook1` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (5, '2018-11-19 17:00:35', 'FALL 2018 MANDATORY HEALTH INS FEE', 1936, 0, -5702.27);

COMMIT;


-- -----------------------------------------------------
-- Data for table `umd-db`.`passbook2`
-- -----------------------------------------------------
START TRANSACTION;
USE `umd-db`;
INSERT INTO `umd-db`.`passbook2` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (1, '2019-04-06 22:21:54', 'PRIOR BALANCE', 50, 0, -50);
INSERT INTO `umd-db`.`passbook2` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (2, '2019-04-10 15:35:39', 'TUITION', 5000, 0, -5050);
INSERT INTO `umd-db`.`passbook2` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (3, '2019-04-26 17:51:47', 'HEALTH CENTER VISIT CO-PAY', 25, 0, -5075);
INSERT INTO `umd-db`.`passbook2` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (4, '2019-04-26 17:52:31', 'Payment', 0, 25, -5050);
INSERT INTO `umd-db`.`passbook2` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (5, '2019-04-26 20:42:20', 'ON-CAMPUS PARKING', 400, 0, -5450);

COMMIT;


-- -----------------------------------------------------
-- Data for table `umd-db`.`passbook3`
-- -----------------------------------------------------
START TRANSACTION;
USE `umd-db`;
INSERT INTO `umd-db`.`passbook3` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (1, '2018-12-26 18:32:59', 'PRIOR BALANCE', 50, 0, -50);
INSERT INTO `umd-db`.`passbook3` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (2, '2018-12-26 18:34:54', 'Payment', 0, 50, 0);
INSERT INTO `umd-db`.`passbook3` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (3, '2019-02-27 18:35:08', 'TUITION', 2500, 0, -2500);
INSERT INTO `umd-db`.`passbook3` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (4, '2019-02-27 18:35:20', 'ON-CAMPUS ROOM', 3000, 0, -5500);
INSERT INTO `umd-db`.`passbook3` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (5, '2019-02-27 18:35:30', 'ON-CAMPUS DINNING', 2500, 0, -8000);

COMMIT;


-- -----------------------------------------------------
-- Data for table `umd-db`.`passbook4`
-- -----------------------------------------------------
START TRANSACTION;
USE `umd-db`;
INSERT INTO `umd-db`.`passbook4` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (1, '2019-03-26 18:23:03', 'TUITION', 2500, 0, -2500);
INSERT INTO `umd-db`.`passbook4` (`trans_id`, `trans_date`, `remarks`, `debit`, `credit`, `balance`) VALUES (2, '2019-03-26 18:42:41', 'Payment', 0, 2500, 0);

COMMIT;

